### ISSUE TITLE
What happened to commit history?

### ISSUE THREAD

**Issue by snird** [TryGhost/Ease#28] opened 2022-08-14 19:53 UTC
Why has the commit history been completely deleted?

This is one of the most used themes, and coincidentally - one of the most adapted.
Updating a "fork" is now impossible

**Comment by ErisDS** [comment] 2022-08-15 18:58
Closing as a duplicate of https://github.com/TryGhost/Themes/issues/134 we'll respond soon on the monorepo

**Closed by ErisDS** 2022-08-15 18:58 UTC
