### ISSUE TITLE
Search excerpt is undefined

### ISSUE THREAD

**Issue by zutrinken** [TryGhost/Ease#22] opened 2022-01-25 23:39 UTC
Running ghost 4.33.1, the search only works for title and url, but excerpt stays undefined.

**Comment by minimaluminium** [comment] 2022-03-18 02:59
Hey @zutrinken, I couldn't reproduce the issue. Is this something related with the mentioned Attila theme?

It'd help if you could elaborate more :)

**Comment by minimaluminium** [comment] 2022-04-12 07:14
Couldn't reproduce this in Ease theme, closing the issue for now.

**Closed by minimaluminium** 2022-04-12 07:14 UTC
